name: Publish Firecrawl Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io  # or docker.io
  IMAGE_NAMESPACE: danieluhlik  # change this

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for ghcr.io
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push firecrawl-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/firecrawl-api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/firecrawl-api:latest

      - name: Build and push firecrawl-scraper
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/firecrawl-scraper/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/firecrawl-scraper:latest

      - name: Build and push firecrawl-web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/firecrawl-web/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/firecrawl-web:latest
